### PR TITLE
Added 3 new noses and a pair of glasses

### PR DESCRIPTION
**Pull request by ddemas**
triangle_glasses
nostril_nose_face
pig nose
pointy_nose_face
pointy_nose_triangle_face
round_glasses

### CODE REVIEW

**Comment by ddemas** [comment]
Oh, I didn't see your latest commit lol

**Comment by Twoods01** [comment]
I love the glasses!

I'm not sure which commit you were developing against but I did just change the size of faces as well so you might want to re-test against the current head. Then I would say ditch the 2 dots and the sideways triangle and we can pull in the glasses and the pig nose.

Side note, I'm thinking I'll add anchors for ears pretty soon which should be useful for making the glasses go to the right place on all the faces.

**Comment by ddemas** [comment]
Okay, I double checked and my things still look good with the new head size.

**Comment by Twoods01** [comment]
http://devo.facey.link/39021

:)

**Pull request merged**
